# Generated by Django 3.2.4 on 2021-06-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210617_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField()),
                ('rodzajFilmu', models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Dramat'), (3, 'Komedia'), (2, 'Sci-Fi')])),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extrainfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.extrainfo'),
        ),
    ]
