# Generated by Django 3.2.4 on 2021-06-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210617_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzajFilmu',
            field=models.IntegerField(choices=[(2, 'Sci-Fi'), (1, 'Dramat'), (3, 'Komedia'), (0, 'Nieznany')]),
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(default='')),
                ('gwiazdki', models.IntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
        ),
    ]
