# Generated by Django 3.2.4 on 2021-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210617_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzajFilmu',
            field=models.IntegerField(choices=[(2, 'Sci-Fi'), (1, 'Dramat'), (3, 'Komedia'), (0, 'Nieznany')]),
        ),
    ]
